// frontend/react-app/src/hooks/Navbar/Navbar.js
import React from 'react';
import './Navbar.css';
import iconImage from '../../assets/images/icon.png'; 

function Navbar() {
  return (
    <nav className="navbar navbar-custom navbar-expand-lg">
      <div className="container-fluid">
        <a className="navbar-brand" href="#">
            <img src={iconImage} alt="Icon" width="40" className="d-inline-block align-text-top" />
        </a>
        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span className="navbar-toggler-icon"></span>
        </button>
        <div className="collapse navbar-collapse" id="navbarNav">
          <ul className="navbar-nav me-auto">
            <li className="nav-item">
              <a className="nav-link active" aria-current="page" href="#">Home</a>
            </li>
          </ul>
          <ul className="navbar-nav ms-auto">
            <li className="nav-item">
              <a className="nav-link" href="/login"><i className="bi bi-box-arrow-in-right"></i> Login</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  );
}

export default Navbar;

// frontend/angular-project/src/app/core/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../../auth.service';
import { NgIf } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [NgIf],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  isLoggedIn = false;

  constructor(private authService: AuthService) {}

  ngOnInit() {
    this.isLoggedIn = this.authService.isLoggedIn();
    this.authService.isLoggedIn$.subscribe(isLoggedIn => {
      this.isLoggedIn = isLoggedIn;
    });
  }

  logout() {
    this.authService.logout();
    this.isLoggedIn = false;
  }

}

<nav class="navbar navbar-custom navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="assets/icon.png" alt="Icon" width="40" class="d-inline-block align-text-top">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item" *ngIf="isLoggedIn">
            <a class="nav-link active" aria-current="page" href="/edit-routes">Editare rute</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item" *ngIf="!isLoggedIn">
            <a class="nav-link" href="/login"><i class="bi bi-box-arrow-in-right"></i> Login</a>
          </li>
          <li class="nav-item" *ngIf="isLoggedIn">
            <a class="nav-link" (click)="logout()"><i class="bi bi-box-arrow-right"></i> Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
